apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  namespace: {{ .Values.namespace | quote }}
type: Opaque
data:
{{- if .Values.secrets }}
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | quote | b64enc }}
{{- end }}
{{- end }}
